site_name: "Home Assistant Community Store"
site_short_name: "HACS"
site_favicon_location: "https://brands.home-assistant.io/hacs/icon.png"

github_branch: "experimental"
github_repository: "hacs/documentation"

twitter_username: "@HACSIntegration"

navigation:
  - name: Users
    path: /users
  - name: Publishers
    path: /publishers
  - name: Blog
    path: /blog
  - name: FAQ
    path: /faq
  - name: Help
    path: /help

footer:
  - title: GitHub
    url: "/github"
  - title: Twitter
    url: "/twitter"
  - title: Discord
    url: "/discord"
  - title: Code of Conduct
    url: "https://github.com/hacs/.github/blob/master/CODE_OF_CONDUCT.md"
  - title: "Contact (no support!)"
    url: "mailto:hi@hacs.xyz"
